title: Home Assistant - сервер
views:

  - title: Главная
    icon: mdi:home-assistant
    
    cards:

      - type: vertical-stack
        cards:
        
        - type: markdown
          content: >
             **Текущее состояние**
             
        - type: entities
          show_header_toggle: false
          entities:
            - entity: sensor.last_boot_custom
            - entity: sensor.online_custom
            - entity: sensor.time
              name: Текущее время
              icon: mdi:clock-outline
            - entity: sensor.date
              name: Дата
              icon: mdi:calendar-check-outline
            - entity: sensor.rpi_power_status
              
        - type: markdown
          content: >
             **Резервное копирование**
             
        - type: entities
          show_header_toggle: false
          entities:
            - entity: sensor.last_google_backup_train
            - entity: sensor.snapshots_in_google_drive_train
            - entity: sensor.snapshots_in_hassio_train
              
        - type: entities
          show_header_toggle: false
          entities:
            - entity: sensor.maria_db_size
              name: Объем БД
              icon: mdi:database

      - type: vertical-stack
        cards:
        - type: markdown
          content: >
             **Графики** 
        - type: horizontal-stack
          cards:

           - type: gauge
             name: Загрузка CPU
             unit: '%'
             entity: sensor.processor_use
             severity:
                green: 0
                yellow: 60
                red: 85
             
           - type: gauge
             name: Загрузка ОЗУ
             unit: '%'
             entity: sensor.memory_use_percent
             severity:
                green: 0
                yellow: 60
                red: 85
                
        - type: horizontal-stack
          cards:

           - type: gauge
             name: Диск заполнен
             unit: '%'
             entity: sensor.disk_use_percent
             severity:
                green: 0
                yellow: 60
                red: 85    
                
           - type: gauge
             name: Свободное место
             unit: 'Гб'
             entity: sensor.disk_free
             severity:
                red: 2
                yellow: 6
                green: 8
                
        - type: history-graph
          entities:
           - entity: sensor.maria_db_size
             name: Maria DB
                
              
  - title: Погода
    icon: mdi:weather-partly-snowy-rainy
    
    cards:

        - type: weather-forecast
          entity: weather.home_assistant 
          
          
  - title: Освещение
    icon: mdi:lightbulb-group
    
          
    cards:
    
      - type: vertical-stack
        cards:
        - type: markdown
          content: >
             **Панель переключателей** 
             
        - type: entities
          show_header_toggle: false
          entities:          
            - entity: light.yeelight_650
              name: Люстра 650 основной свет
            - entity: light.yeelight_650_nightlight
              name: Люстра 650 ночник
            - entity: light.yeelight_650_ambilight
              name: Люстра 650 амбилайт           
            - entity: light.yeelight_450           
              name: Люстра 450 основной свет
            - entity: light.yeelight_450_nightlight 
              name: Люстра 450 ночник            
            - entity: light.yeelight_rgb_bulb            
              name: Лампочка  
            - entity: light.philips_ceiling           
              name: Philips люстра
            - entity: light.philips_bedside
              name: Philips прикроватник   
              
        - type: entities
          show_header_toggle: false
          entities:          
            - entity: script.unit8_light_on_full
            - entity: script.unit8_light_on_medium
            - entity: script.unit8_light_off

              
      - type: vertical-stack
        cards:
        - type: markdown
          content: >
             **Светильники**    
              
        - type: horizontal-stack
          cards:
            - type: light
              entity: light.yeelight_650
              name: Люстра 650
            - type: light
              entity: light.yeelight_650_nightlight
              name: Ночник 650
            - type: light
              entity: light.yeelight_650_ambilight
              name: Ambilight 650
              
        - type: horizontal-stack
          cards:
            - type: light
              entity: light.yeelight_450
              name: Люстра 450
            - type: light
              entity: light.yeelight_450_nightlight
              name: Ночник 450
            - type: light
              entity: light.yeelight_rgb_bulb
              name: RGB Лампочка 
        - type: horizontal-stack
          cards:
            - type: light
              entity: light.philips_ceiling 
              name: Люстра
            - type: light
              entity: light.philips_bedside
              name: Прикроватник

  - title: Zigbee
    icon: mdi:zigbee
    
    cards:
    
      - type: vertical-stack
        cards:
        - type: markdown
          content: >
             **Уровень заряда** 
             
        - type: entities
          show_header_toggle: false
          entities:          
            - entity: sensor.158d0001531698_battery
            - entity: sensor.158d0001186d82_battery
            - entity: sensor.158d00013fc3bc_battery
            
        - type: markdown
          content: >
             **Розетки** 
             
        - type: entities
          show_header_toggle: false
          entities:          
            - entity: switch.plug_158d00010ec4b8
            - entity: sensor.158d00010ec4b8_load
              
        - type: markdown
          content: >
             **Шлюз** 
             
        - type: entities
          show_header_toggle: false
          entities:          
            - entity: light.gateway_light_34ce0088b039
            - entity: sensor.illumination_34ce0088b039

      - type: vertical-stack
        cards:
        - type: markdown
          content: >
             **Климат, окна двери** 
             
        - type: entities
          show_header_toggle: false
          entities:   
            - entity: sensor.humidity_158d00015aebb6
            - entity: sensor.temperature_158d00015aebb6
            - entity: binary_sensor.door_window_sensor_158d00013ed373
            - entity: binary_sensor.door_window_sensor_158d000445206b
        
  - title: СС 2531
    icon: mdi:usb-flash-drive
    
    cards:
    
      - type: vertical-stack
        cards:
        - type: markdown
          content: >
             **Добавление устройств**     
        - type: entities
          title: Добавление Zigbee устройств
          show_header_toggle: false
          entities:
             - entity: input_boolean.zigbee_permit_join
             - entity: timer.zigbee_permit_join
             - entity: sensor.bridge_state

            
        - type: markdown
          content: >
             **Розетки и реле** 
             
        - type: entities
          show_header_toggle: false
          entities:          
            - entity: switch.dd_wd_n_2ch_switch_left
            - entity: switch.dd_wd_n_2ch_switch_right
            - entity: sensor.dd_wd_n_2ch_power
            
  - title: wi-fi
    icon: mdi:wifi
    
    cards:
    
      - type: vertical-stack
        cards:
        - type: markdown
          content: >
             **Wi-Fi розетки и удлинители**  
        - type: entities
          show_header_toggle: false
          entities:          
            - entity: switch.mi_3usb_strip
              name: Удлинитель Xiaomi c 3 USB
              secondary_info: last-changed
            - entity: sensor.mi_3usb_strip_load
            - entity: switch.mi_usb_socket
              name: Розетка Xiaomi c 2 USB
            - entity: sensor.usb_socket_load
          
      - type: vertical-stack
        cards:
        - type: markdown
          content: >
             **Климатическая техника**  
        - type: entities
          show_header_toggle: false
          entities:          
            - entity: fan.mi_humidifier
              name: Увлажнитель Smartmi
            - entity: sensor.smartmi_speed 
            - entity: sensor.smartmi_water
            - entity: sensor.smartmi_temperature 
            - entity: sensor.smartmi_humidity
            
        - type: entities
          show_header_toggle: false
          entities:          
            - entity: fan.mi_purifier
              name: Очиститель Xiaomi           
            - entity: sensor.purifier_speed
            - entity: sensor.purifier_filter
            - entity: sensor.purifier_temperature
            - entity: sensor.purifier_humidity
            - entity: sensor.purifier_pm25
          
      - type: vertical-stack
        cards:
        - type: markdown
          content: >
             **Качество воздуха**  
        - type: entities
          show_header_toggle: false
          entities:          
            - entity: sensor.mi_air_co2a 
            - entity: sensor.mi_air_pm25
            - entity: sensor.mi_air_tvoc
          
  - title: Шаблоны
    icon: mdi:alpha-t-box
    
    cards:
    
      - type: vertical-stack
        cards:
  
        - type: markdown
          content: >
             **Составной сенсор движения**          
        - type: glance  
          show_state: false
          entities:
             - entity: binary_sensor.ln_moving_occupancy
               name: Движение 1
             - entity: binary_sensor.cr_moving_occupancy
               name: Движение 2
             - entity: binary_sensor.lr_balcony_moving_occupancy
               name: Движение 3

        - type: glance
          show_state: false
          entities:
             - entity: binary_sensor.super_motion

        - type: markdown
          content: >
             **Составной сенсор окон**   
             
        - type: glance  
          show_state: false
          entities:
             - entity: binary_sensor.dd_window_contact
               name: Окно 1
             - entity: binary_sensor.da_window_contact
               name: Окно 2
             - entity: binary_sensor.lr_window_contact
               name: Окно 3
          
        - type: glance
          show_state: false
          entities:
             - entity: binary_sensor.super_windows
 
      - type: vertical-stack
        cards:     

        - type: markdown
          content: >
             **Составной сенсор для увлажнения**  
        
        - type: glance  
          entities:
             - entity: binary_sensor.tod_day
               name: Дневное время
             - entity: sensor.kn_climate_humidity
               name: Влажность
               
        - type: glance
          show_state: false
          entities:
             - entity: binary_sensor.super_windows_day

        - type: markdown
          content: >
             **Сенсоры светильников**  
        - type: entities
          show_header_toggle: false
          entities:
             - entity: light.philips_bedside
               name: Светильник
             - entity: binary_sensor.cr_moving_occupancy
               name: Движение
             - entity: binary_sensor.auto_light

        - type: markdown
          content: >
             **Нагрузка**  
             
        - type: entities
          show_header_toggle: false
          entities:
             - entity: switch.mi_3usb_strip
             - entity: sensor.mi_3usb_strip_load
             - entity: binary_sensor.check_load
               
          
  - title: Packages
    icon: mdi:package-variant
    
    cards:
        - type: entities
          show_header_toggle: false
          entities:
             - entity: light.yeelight_320_ceiling
               name: Светильник
             - entity: binary_sensor.0x00158d0001a24e71_occupancy
               name: Движение
             - entity: binary_sensor.unit_10_1_ex1
             - entity: binary_sensor.unit_10_1_ex1_day
               name: День
             - entity: binary_sensor.unit_10_1_ex1_night
               name: Ночь 
             - entity: timer.unit_10_1_ex1


        - type: entities
          show_header_toggle: false
          state_color: true
          entities:
             - entity: light.yeelight_450
               name: Светильник 2
             - entity: binary_sensor.ln_moving_occupancy
               name: Движение
             - entity: binary_sensor.unit_10_1_ex2
             - entity: sensor.kn_light_sensor_illuminance
               name: Освещенность